# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-13 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='original_price',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
