# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-14 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model01', '0004_auto_20181113_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 't_test',
            },
        ),
    ]
