# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-14 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(max_length=64, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=1)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('emp_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'emp',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_img', models.CharField(max_length=100)),
                ('goods_name', models.CharField(max_length=100)),
                ('goods_info', models.CharField(max_length=255)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('goods_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
