# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-14 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
