# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model02', '0002_emp_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
